version: '3'
services:
  db:
    image: postgres
    env_file:
      - '.env'
    ports:
      - "8000:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5
  web:
    restart: always
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      db:
        condition: service_healthy
    expose:
      - 8000
  nginx:
    build: ./nginx
    volumes:
      - ./pages/static:/etc/nginx/static
    ports:
      - '80:80'
    depends_on:
      - web
