version: '3'
services:
  db:
    image: postgres
    env_file:
      - '.env'
    ports:
      - "8000:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5
  web:
    restart: always
    build: .
    volumes:
      - .:/home_library
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "80:8000"
