# Generated by Django 4.2.7 on 2024-01-05 21:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tbr',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=512, null=True), default=[], size=None),
            preserve_default=False,
        ),
    ]
