# Generated by Django 4.2.7 on 2024-02-20 22:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_tbr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tbr',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=512), size=None),
        ),
    ]
